notifications:
  createIssues:
    repository: "yrodiere/quarkus-github-playground-lottery-reports"
labels:
  needsTriage: "triage/needs-triage"
participants:
  - username: "yrodiere"
    when: ["MONDAY"]
    triage:
      maxIssues: 3
