notifications:
  createIssues:
    repository: "yrodiere/quarkus-github-playground-lottery-reports"
buckets:
  triage:
    needsTriageLabel: "triage/needs-triage"
    notificationExpiration: P3D
labels:
  needsTriage: "triage/needs-triage"
participants:
  - username: "yrodiere"
    days: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"]
    triage:
      maxIssues: 3
